// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Logflare
{
    [LogflareResourceType("logflare:index/endpoint:Endpoint")]
    public partial class Endpoint : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Cache duration in seconds
        /// </summary>
        [Output("cacheDurationSeconds")]
        public Output<int> CacheDurationSeconds { get; private set; } = null!;

        /// <summary>
        /// Description of the endpoint
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Enable authentication for the endpoint
        /// </summary>
        [Output("enableAuth")]
        public Output<bool> EnableAuth { get; private set; } = null!;

        /// <summary>
        /// Maximum limit
        /// </summary>
        [Output("maxLimit")]
        public Output<int> MaxLimit { get; private set; } = null!;

        /// <summary>
        /// Name of the endpoint
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Proactive requerying interval in seconds
        /// </summary>
        [Output("proactiveRequeryingSeconds")]
        public Output<int> ProactiveRequeryingSeconds { get; private set; } = null!;

        /// <summary>
        /// Query string
        /// </summary>
        [Output("query")]
        public Output<string> Query { get; private set; } = null!;

        /// <summary>
        /// Whether the endpoint is sandboxable
        /// </summary>
        [Output("sandboxable")]
        public Output<bool> Sandboxable { get; private set; } = null!;

        /// <summary>
        /// Source mapping as JSON
        /// </summary>
        [Output("sourceMapping")]
        public Output<string> SourceMapping { get; private set; } = null!;

        /// <summary>
        /// Authentication token
        /// </summary>
        [Output("token")]
        public Output<string> Token { get; private set; } = null!;


        /// <summary>
        /// Create a Endpoint resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Endpoint(string name, EndpointArgs args, CustomResourceOptions? options = null)
            : base("logflare:index/endpoint:Endpoint", name, args ?? new EndpointArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Endpoint(string name, Input<string> id, EndpointState? state = null, CustomResourceOptions? options = null)
            : base("logflare:index/endpoint:Endpoint", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "token",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Endpoint resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Endpoint Get(string name, Input<string> id, EndpointState? state = null, CustomResourceOptions? options = null)
        {
            return new Endpoint(name, id, state, options);
        }
    }

    public sealed class EndpointArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cache duration in seconds
        /// </summary>
        [Input("cacheDurationSeconds")]
        public Input<int>? CacheDurationSeconds { get; set; }

        /// <summary>
        /// Description of the endpoint
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Enable authentication for the endpoint
        /// </summary>
        [Input("enableAuth")]
        public Input<bool>? EnableAuth { get; set; }

        /// <summary>
        /// Maximum limit
        /// </summary>
        [Input("maxLimit")]
        public Input<int>? MaxLimit { get; set; }

        /// <summary>
        /// Name of the endpoint
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Proactive requerying interval in seconds
        /// </summary>
        [Input("proactiveRequeryingSeconds")]
        public Input<int>? ProactiveRequeryingSeconds { get; set; }

        /// <summary>
        /// Query string
        /// </summary>
        [Input("query", required: true)]
        public Input<string> Query { get; set; } = null!;

        /// <summary>
        /// Whether the endpoint is sandboxable
        /// </summary>
        [Input("sandboxable")]
        public Input<bool>? Sandboxable { get; set; }

        /// <summary>
        /// Source mapping as JSON
        /// </summary>
        [Input("sourceMapping")]
        public Input<string>? SourceMapping { get; set; }

        public EndpointArgs()
        {
        }
        public static new EndpointArgs Empty => new EndpointArgs();
    }

    public sealed class EndpointState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cache duration in seconds
        /// </summary>
        [Input("cacheDurationSeconds")]
        public Input<int>? CacheDurationSeconds { get; set; }

        /// <summary>
        /// Description of the endpoint
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Enable authentication for the endpoint
        /// </summary>
        [Input("enableAuth")]
        public Input<bool>? EnableAuth { get; set; }

        /// <summary>
        /// Maximum limit
        /// </summary>
        [Input("maxLimit")]
        public Input<int>? MaxLimit { get; set; }

        /// <summary>
        /// Name of the endpoint
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Proactive requerying interval in seconds
        /// </summary>
        [Input("proactiveRequeryingSeconds")]
        public Input<int>? ProactiveRequeryingSeconds { get; set; }

        /// <summary>
        /// Query string
        /// </summary>
        [Input("query")]
        public Input<string>? Query { get; set; }

        /// <summary>
        /// Whether the endpoint is sandboxable
        /// </summary>
        [Input("sandboxable")]
        public Input<bool>? Sandboxable { get; set; }

        /// <summary>
        /// Source mapping as JSON
        /// </summary>
        [Input("sourceMapping")]
        public Input<string>? SourceMapping { get; set; }

        [Input("token")]
        private Input<string>? _token;

        /// <summary>
        /// Authentication token
        /// </summary>
        public Input<string>? Token
        {
            get => _token;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _token = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public EndpointState()
        {
        }
        public static new EndpointState Empty => new EndpointState();
    }
}
