// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Logflare
{
    public static class GetEndpointQuery
    {
        public static Task<GetEndpointQueryResult> InvokeAsync(GetEndpointQueryArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetEndpointQueryResult>("logflare:index/getEndpointQuery:getEndpointQuery", args ?? new GetEndpointQueryArgs(), options.WithDefaults());

        public static Output<GetEndpointQueryResult> Invoke(GetEndpointQueryInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetEndpointQueryResult>("logflare:index/getEndpointQuery:getEndpointQuery", args ?? new GetEndpointQueryInvokeArgs(), options.WithDefaults());

        public static Output<GetEndpointQueryResult> Invoke(GetEndpointQueryInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetEndpointQueryResult>("logflare:index/getEndpointQuery:getEndpointQuery", args ?? new GetEndpointQueryInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetEndpointQueryArgs : global::Pulumi.InvokeArgs
    {
        [Input("nameOrToken", required: true)]
        private string? _nameOrToken;
        public string? NameOrToken
        {
            get => _nameOrToken;
            set => _nameOrToken = value;
        }

        public GetEndpointQueryArgs()
        {
        }
        public static new GetEndpointQueryArgs Empty => new GetEndpointQueryArgs();
    }

    public sealed class GetEndpointQueryInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("nameOrToken", required: true)]
        private Input<string>? _nameOrToken;
        public Input<string>? NameOrToken
        {
            get => _nameOrToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _nameOrToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public GetEndpointQueryInvokeArgs()
        {
        }
        public static new GetEndpointQueryInvokeArgs Empty => new GetEndpointQueryInvokeArgs();
    }


    [OutputType]
    public sealed class GetEndpointQueryResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string NameOrToken;
        public readonly object Result;

        [OutputConstructor]
        private GetEndpointQueryResult(
            string id,

            string nameOrToken,

            object result)
        {
            Id = id;
            NameOrToken = nameOrToken;
            Result = result;
        }
    }
}
