// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Logflare
{
    [LogflareResourceType("logflare:index/source:Source")]
    public partial class Source : global::Pulumi.CustomResource
    {
        /// <summary>
        /// API quota for the source.
        /// </summary>
        [Output("apiQuota")]
        public Output<int> ApiQuota { get; private set; } = null!;

        /// <summary>
        /// BigQuery table Time-To-Live (TTL) in days.
        /// </summary>
        [Output("bigqueryTableTtl")]
        public Output<int> BigqueryTableTtl { get; private set; } = null!;

        /// <summary>
        /// BigQuery table ID.
        /// </summary>
        [Output("bqTableId")]
        public Output<string> BqTableId { get; private set; } = null!;

        /// <summary>
        /// Custom event message keys.
        /// </summary>
        [Output("customEventMessageKeys")]
        public Output<string> CustomEventMessageKeys { get; private set; } = null!;

        /// <summary>
        /// Whether the default ingest backend is enabled.
        /// </summary>
        [Output("defaultIngestBackendEnabled")]
        public Output<bool> DefaultIngestBackendEnabled { get; private set; } = null!;

        /// <summary>
        /// Whether the source is marked as a favorite.
        /// </summary>
        [Output("favorite")]
        public Output<bool> Favorite { get; private set; } = null!;

        /// <summary>
        /// Whether the source has rejected events.
        /// </summary>
        [Output("hasRejectedEvents")]
        public Output<bool> HasRejectedEvents { get; private set; } = null!;

        /// <summary>
        /// Timestamp of when the source was created.
        /// </summary>
        [Output("insertedAt")]
        public Output<string> InsertedAt { get; private set; } = null!;

        /// <summary>
        /// Metrics for the source, as a JSON string.
        /// </summary>
        [Output("metrics")]
        public Output<string> Metrics { get; private set; } = null!;

        /// <summary>
        /// The name of the source.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Notification settings for the source.
        /// </summary>
        [Output("notifications")]
        public Output<Outputs.SourceNotifications> Notifications { get; private set; } = null!;

        /// <summary>
        /// Public token for the source.
        /// </summary>
        [Output("publicToken")]
        public Output<string> PublicToken { get; private set; } = null!;

        /// <summary>
        /// Slack webhook URL for notifications.
        /// </summary>
        [Output("slackHookUrl")]
        public Output<string> SlackHookUrl { get; private set; } = null!;

        /// <summary>
        /// Private token for the source.
        /// </summary>
        [Output("token")]
        public Output<string> Token { get; private set; } = null!;

        /// <summary>
        /// Timestamp of when the source was last updated.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// Webhook URL for notifications.
        /// </summary>
        [Output("webhookNotificationUrl")]
        public Output<string> WebhookNotificationUrl { get; private set; } = null!;


        /// <summary>
        /// Create a Source resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Source(string name, SourceArgs? args = null, CustomResourceOptions? options = null)
            : base("logflare:index/source:Source", name, args ?? new SourceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Source(string name, Input<string> id, SourceState? state = null, CustomResourceOptions? options = null)
            : base("logflare:index/source:Source", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "publicToken",
                    "slackHookUrl",
                    "token",
                    "webhookNotificationUrl",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Source resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Source Get(string name, Input<string> id, SourceState? state = null, CustomResourceOptions? options = null)
        {
            return new Source(name, id, state, options);
        }
    }

    public sealed class SourceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// API quota for the source.
        /// </summary>
        [Input("apiQuota")]
        public Input<int>? ApiQuota { get; set; }

        /// <summary>
        /// BigQuery table Time-To-Live (TTL) in days.
        /// </summary>
        [Input("bigqueryTableTtl")]
        public Input<int>? BigqueryTableTtl { get; set; }

        /// <summary>
        /// BigQuery table ID.
        /// </summary>
        [Input("bqTableId")]
        public Input<string>? BqTableId { get; set; }

        /// <summary>
        /// Custom event message keys.
        /// </summary>
        [Input("customEventMessageKeys")]
        public Input<string>? CustomEventMessageKeys { get; set; }

        /// <summary>
        /// Whether the default ingest backend is enabled.
        /// </summary>
        [Input("defaultIngestBackendEnabled")]
        public Input<bool>? DefaultIngestBackendEnabled { get; set; }

        /// <summary>
        /// Whether the source is marked as a favorite.
        /// </summary>
        [Input("favorite")]
        public Input<bool>? Favorite { get; set; }

        /// <summary>
        /// Metrics for the source, as a JSON string.
        /// </summary>
        [Input("metrics")]
        public Input<string>? Metrics { get; set; }

        /// <summary>
        /// The name of the source.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Notification settings for the source.
        /// </summary>
        [Input("notifications")]
        public Input<Inputs.SourceNotificationsArgs>? Notifications { get; set; }

        [Input("slackHookUrl")]
        private Input<string>? _slackHookUrl;

        /// <summary>
        /// Slack webhook URL for notifications.
        /// </summary>
        public Input<string>? SlackHookUrl
        {
            get => _slackHookUrl;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _slackHookUrl = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("webhookNotificationUrl")]
        private Input<string>? _webhookNotificationUrl;

        /// <summary>
        /// Webhook URL for notifications.
        /// </summary>
        public Input<string>? WebhookNotificationUrl
        {
            get => _webhookNotificationUrl;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _webhookNotificationUrl = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public SourceArgs()
        {
        }
        public static new SourceArgs Empty => new SourceArgs();
    }

    public sealed class SourceState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// API quota for the source.
        /// </summary>
        [Input("apiQuota")]
        public Input<int>? ApiQuota { get; set; }

        /// <summary>
        /// BigQuery table Time-To-Live (TTL) in days.
        /// </summary>
        [Input("bigqueryTableTtl")]
        public Input<int>? BigqueryTableTtl { get; set; }

        /// <summary>
        /// BigQuery table ID.
        /// </summary>
        [Input("bqTableId")]
        public Input<string>? BqTableId { get; set; }

        /// <summary>
        /// Custom event message keys.
        /// </summary>
        [Input("customEventMessageKeys")]
        public Input<string>? CustomEventMessageKeys { get; set; }

        /// <summary>
        /// Whether the default ingest backend is enabled.
        /// </summary>
        [Input("defaultIngestBackendEnabled")]
        public Input<bool>? DefaultIngestBackendEnabled { get; set; }

        /// <summary>
        /// Whether the source is marked as a favorite.
        /// </summary>
        [Input("favorite")]
        public Input<bool>? Favorite { get; set; }

        /// <summary>
        /// Whether the source has rejected events.
        /// </summary>
        [Input("hasRejectedEvents")]
        public Input<bool>? HasRejectedEvents { get; set; }

        /// <summary>
        /// Timestamp of when the source was created.
        /// </summary>
        [Input("insertedAt")]
        public Input<string>? InsertedAt { get; set; }

        /// <summary>
        /// Metrics for the source, as a JSON string.
        /// </summary>
        [Input("metrics")]
        public Input<string>? Metrics { get; set; }

        /// <summary>
        /// The name of the source.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Notification settings for the source.
        /// </summary>
        [Input("notifications")]
        public Input<Inputs.SourceNotificationsGetArgs>? Notifications { get; set; }

        [Input("publicToken")]
        private Input<string>? _publicToken;

        /// <summary>
        /// Public token for the source.
        /// </summary>
        public Input<string>? PublicToken
        {
            get => _publicToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _publicToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("slackHookUrl")]
        private Input<string>? _slackHookUrl;

        /// <summary>
        /// Slack webhook URL for notifications.
        /// </summary>
        public Input<string>? SlackHookUrl
        {
            get => _slackHookUrl;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _slackHookUrl = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("token")]
        private Input<string>? _token;

        /// <summary>
        /// Private token for the source.
        /// </summary>
        public Input<string>? Token
        {
            get => _token;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _token = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Timestamp of when the source was last updated.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        [Input("webhookNotificationUrl")]
        private Input<string>? _webhookNotificationUrl;

        /// <summary>
        /// Webhook URL for notifications.
        /// </summary>
        public Input<string>? WebhookNotificationUrl
        {
            get => _webhookNotificationUrl;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _webhookNotificationUrl = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public SourceState()
        {
        }
        public static new SourceState Empty => new SourceState();
    }
}
