// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package logflare

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/supabase/pulumi-supabase-analytics/sdk/go/logflare/internal"
)

type Endpoint struct {
	pulumi.CustomResourceState

	// Cache duration in seconds
	CacheDurationSeconds pulumi.IntOutput `pulumi:"cacheDurationSeconds"`
	// Description of the endpoint
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Enable authentication for the endpoint
	EnableAuth pulumi.BoolOutput `pulumi:"enableAuth"`
	// Maximum limit
	MaxLimit pulumi.IntOutput `pulumi:"maxLimit"`
	// Name of the endpoint
	Name pulumi.StringOutput `pulumi:"name"`
	// Proactive requerying interval in seconds
	ProactiveRequeryingSeconds pulumi.IntOutput `pulumi:"proactiveRequeryingSeconds"`
	// Query string
	Query pulumi.StringOutput `pulumi:"query"`
	// Whether the endpoint is sandboxable
	Sandboxable pulumi.BoolOutput `pulumi:"sandboxable"`
	// Source mapping as JSON
	SourceMapping pulumi.StringOutput `pulumi:"sourceMapping"`
	// Authentication token
	Token pulumi.StringOutput `pulumi:"token"`
}

// NewEndpoint registers a new resource with the given unique name, arguments, and options.
func NewEndpoint(ctx *pulumi.Context,
	name string, args *EndpointArgs, opts ...pulumi.ResourceOption) (*Endpoint, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Query == nil {
		return nil, errors.New("invalid value for required argument 'Query'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Endpoint
	err := ctx.RegisterResource("logflare:index/endpoint:Endpoint", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEndpoint gets an existing Endpoint resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEndpoint(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EndpointState, opts ...pulumi.ResourceOption) (*Endpoint, error) {
	var resource Endpoint
	err := ctx.ReadResource("logflare:index/endpoint:Endpoint", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Endpoint resources.
type endpointState struct {
	// Cache duration in seconds
	CacheDurationSeconds *int `pulumi:"cacheDurationSeconds"`
	// Description of the endpoint
	Description *string `pulumi:"description"`
	// Enable authentication for the endpoint
	EnableAuth *bool `pulumi:"enableAuth"`
	// Maximum limit
	MaxLimit *int `pulumi:"maxLimit"`
	// Name of the endpoint
	Name *string `pulumi:"name"`
	// Proactive requerying interval in seconds
	ProactiveRequeryingSeconds *int `pulumi:"proactiveRequeryingSeconds"`
	// Query string
	Query *string `pulumi:"query"`
	// Whether the endpoint is sandboxable
	Sandboxable *bool `pulumi:"sandboxable"`
	// Source mapping as JSON
	SourceMapping *string `pulumi:"sourceMapping"`
	// Authentication token
	Token *string `pulumi:"token"`
}

type EndpointState struct {
	// Cache duration in seconds
	CacheDurationSeconds pulumi.IntPtrInput
	// Description of the endpoint
	Description pulumi.StringPtrInput
	// Enable authentication for the endpoint
	EnableAuth pulumi.BoolPtrInput
	// Maximum limit
	MaxLimit pulumi.IntPtrInput
	// Name of the endpoint
	Name pulumi.StringPtrInput
	// Proactive requerying interval in seconds
	ProactiveRequeryingSeconds pulumi.IntPtrInput
	// Query string
	Query pulumi.StringPtrInput
	// Whether the endpoint is sandboxable
	Sandboxable pulumi.BoolPtrInput
	// Source mapping as JSON
	SourceMapping pulumi.StringPtrInput
	// Authentication token
	Token pulumi.StringPtrInput
}

func (EndpointState) ElementType() reflect.Type {
	return reflect.TypeOf((*endpointState)(nil)).Elem()
}

type endpointArgs struct {
	// Cache duration in seconds
	CacheDurationSeconds *int `pulumi:"cacheDurationSeconds"`
	// Description of the endpoint
	Description *string `pulumi:"description"`
	// Enable authentication for the endpoint
	EnableAuth *bool `pulumi:"enableAuth"`
	// Maximum limit
	MaxLimit *int `pulumi:"maxLimit"`
	// Name of the endpoint
	Name *string `pulumi:"name"`
	// Proactive requerying interval in seconds
	ProactiveRequeryingSeconds *int `pulumi:"proactiveRequeryingSeconds"`
	// Query string
	Query string `pulumi:"query"`
	// Whether the endpoint is sandboxable
	Sandboxable *bool `pulumi:"sandboxable"`
	// Source mapping as JSON
	SourceMapping *string `pulumi:"sourceMapping"`
}

// The set of arguments for constructing a Endpoint resource.
type EndpointArgs struct {
	// Cache duration in seconds
	CacheDurationSeconds pulumi.IntPtrInput
	// Description of the endpoint
	Description pulumi.StringPtrInput
	// Enable authentication for the endpoint
	EnableAuth pulumi.BoolPtrInput
	// Maximum limit
	MaxLimit pulumi.IntPtrInput
	// Name of the endpoint
	Name pulumi.StringPtrInput
	// Proactive requerying interval in seconds
	ProactiveRequeryingSeconds pulumi.IntPtrInput
	// Query string
	Query pulumi.StringInput
	// Whether the endpoint is sandboxable
	Sandboxable pulumi.BoolPtrInput
	// Source mapping as JSON
	SourceMapping pulumi.StringPtrInput
}

func (EndpointArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*endpointArgs)(nil)).Elem()
}

type EndpointInput interface {
	pulumi.Input

	ToEndpointOutput() EndpointOutput
	ToEndpointOutputWithContext(ctx context.Context) EndpointOutput
}

func (*Endpoint) ElementType() reflect.Type {
	return reflect.TypeOf((**Endpoint)(nil)).Elem()
}

func (i *Endpoint) ToEndpointOutput() EndpointOutput {
	return i.ToEndpointOutputWithContext(context.Background())
}

func (i *Endpoint) ToEndpointOutputWithContext(ctx context.Context) EndpointOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EndpointOutput)
}

// EndpointArrayInput is an input type that accepts EndpointArray and EndpointArrayOutput values.
// You can construct a concrete instance of `EndpointArrayInput` via:
//
//	EndpointArray{ EndpointArgs{...} }
type EndpointArrayInput interface {
	pulumi.Input

	ToEndpointArrayOutput() EndpointArrayOutput
	ToEndpointArrayOutputWithContext(context.Context) EndpointArrayOutput
}

type EndpointArray []EndpointInput

func (EndpointArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Endpoint)(nil)).Elem()
}

func (i EndpointArray) ToEndpointArrayOutput() EndpointArrayOutput {
	return i.ToEndpointArrayOutputWithContext(context.Background())
}

func (i EndpointArray) ToEndpointArrayOutputWithContext(ctx context.Context) EndpointArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EndpointArrayOutput)
}

// EndpointMapInput is an input type that accepts EndpointMap and EndpointMapOutput values.
// You can construct a concrete instance of `EndpointMapInput` via:
//
//	EndpointMap{ "key": EndpointArgs{...} }
type EndpointMapInput interface {
	pulumi.Input

	ToEndpointMapOutput() EndpointMapOutput
	ToEndpointMapOutputWithContext(context.Context) EndpointMapOutput
}

type EndpointMap map[string]EndpointInput

func (EndpointMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Endpoint)(nil)).Elem()
}

func (i EndpointMap) ToEndpointMapOutput() EndpointMapOutput {
	return i.ToEndpointMapOutputWithContext(context.Background())
}

func (i EndpointMap) ToEndpointMapOutputWithContext(ctx context.Context) EndpointMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EndpointMapOutput)
}

type EndpointOutput struct{ *pulumi.OutputState }

func (EndpointOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Endpoint)(nil)).Elem()
}

func (o EndpointOutput) ToEndpointOutput() EndpointOutput {
	return o
}

func (o EndpointOutput) ToEndpointOutputWithContext(ctx context.Context) EndpointOutput {
	return o
}

// Cache duration in seconds
func (o EndpointOutput) CacheDurationSeconds() pulumi.IntOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.IntOutput { return v.CacheDurationSeconds }).(pulumi.IntOutput)
}

// Description of the endpoint
func (o EndpointOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Enable authentication for the endpoint
func (o EndpointOutput) EnableAuth() pulumi.BoolOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.BoolOutput { return v.EnableAuth }).(pulumi.BoolOutput)
}

// Maximum limit
func (o EndpointOutput) MaxLimit() pulumi.IntOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.IntOutput { return v.MaxLimit }).(pulumi.IntOutput)
}

// Name of the endpoint
func (o EndpointOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Proactive requerying interval in seconds
func (o EndpointOutput) ProactiveRequeryingSeconds() pulumi.IntOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.IntOutput { return v.ProactiveRequeryingSeconds }).(pulumi.IntOutput)
}

// Query string
func (o EndpointOutput) Query() pulumi.StringOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringOutput { return v.Query }).(pulumi.StringOutput)
}

// Whether the endpoint is sandboxable
func (o EndpointOutput) Sandboxable() pulumi.BoolOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.BoolOutput { return v.Sandboxable }).(pulumi.BoolOutput)
}

// Source mapping as JSON
func (o EndpointOutput) SourceMapping() pulumi.StringOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringOutput { return v.SourceMapping }).(pulumi.StringOutput)
}

// Authentication token
func (o EndpointOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *Endpoint) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

type EndpointArrayOutput struct{ *pulumi.OutputState }

func (EndpointArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Endpoint)(nil)).Elem()
}

func (o EndpointArrayOutput) ToEndpointArrayOutput() EndpointArrayOutput {
	return o
}

func (o EndpointArrayOutput) ToEndpointArrayOutputWithContext(ctx context.Context) EndpointArrayOutput {
	return o
}

func (o EndpointArrayOutput) Index(i pulumi.IntInput) EndpointOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Endpoint {
		return vs[0].([]*Endpoint)[vs[1].(int)]
	}).(EndpointOutput)
}

type EndpointMapOutput struct{ *pulumi.OutputState }

func (EndpointMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Endpoint)(nil)).Elem()
}

func (o EndpointMapOutput) ToEndpointMapOutput() EndpointMapOutput {
	return o
}

func (o EndpointMapOutput) ToEndpointMapOutputWithContext(ctx context.Context) EndpointMapOutput {
	return o
}

func (o EndpointMapOutput) MapIndex(k pulumi.StringInput) EndpointOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Endpoint {
		return vs[0].(map[string]*Endpoint)[vs[1].(string)]
	}).(EndpointOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EndpointInput)(nil)).Elem(), &Endpoint{})
	pulumi.RegisterInputType(reflect.TypeOf((*EndpointArrayInput)(nil)).Elem(), EndpointArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*EndpointMapInput)(nil)).Elem(), EndpointMap{})
	pulumi.RegisterOutputType(EndpointOutput{})
	pulumi.RegisterOutputType(EndpointArrayOutput{})
	pulumi.RegisterOutputType(EndpointMapOutput{})
}
