// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package logflare

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/supabase/pulumi-supabase-analytics/sdk/go/logflare/internal"
)

func GetEndpointQuery(ctx *pulumi.Context, args *GetEndpointQueryArgs, opts ...pulumi.InvokeOption) (*GetEndpointQueryResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetEndpointQueryResult
	err := ctx.Invoke("logflare:index/getEndpointQuery:getEndpointQuery", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getEndpointQuery.
type GetEndpointQueryArgs struct {
	NameOrToken string `pulumi:"nameOrToken"`
}

// A collection of values returned by getEndpointQuery.
type GetEndpointQueryResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id          string      `pulumi:"id"`
	NameOrToken string      `pulumi:"nameOrToken"`
	Result      interface{} `pulumi:"result"`
}

func GetEndpointQueryOutput(ctx *pulumi.Context, args GetEndpointQueryOutputArgs, opts ...pulumi.InvokeOption) GetEndpointQueryResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetEndpointQueryResultOutput, error) {
			args := v.(GetEndpointQueryArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("logflare:index/getEndpointQuery:getEndpointQuery", args, GetEndpointQueryResultOutput{}, options).(GetEndpointQueryResultOutput), nil
		}).(GetEndpointQueryResultOutput)
}

// A collection of arguments for invoking getEndpointQuery.
type GetEndpointQueryOutputArgs struct {
	NameOrToken pulumi.StringInput `pulumi:"nameOrToken"`
}

func (GetEndpointQueryOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEndpointQueryArgs)(nil)).Elem()
}

// A collection of values returned by getEndpointQuery.
type GetEndpointQueryResultOutput struct{ *pulumi.OutputState }

func (GetEndpointQueryResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEndpointQueryResult)(nil)).Elem()
}

func (o GetEndpointQueryResultOutput) ToGetEndpointQueryResultOutput() GetEndpointQueryResultOutput {
	return o
}

func (o GetEndpointQueryResultOutput) ToGetEndpointQueryResultOutputWithContext(ctx context.Context) GetEndpointQueryResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetEndpointQueryResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetEndpointQueryResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetEndpointQueryResultOutput) NameOrToken() pulumi.StringOutput {
	return o.ApplyT(func(v GetEndpointQueryResult) string { return v.NameOrToken }).(pulumi.StringOutput)
}

func (o GetEndpointQueryResultOutput) Result() pulumi.AnyOutput {
	return o.ApplyT(func(v GetEndpointQueryResult) interface{} { return v.Result }).(pulumi.AnyOutput)
}

func init() {
	pulumi.RegisterOutputType(GetEndpointQueryResultOutput{})
}
