// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package logflare

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/supabase/pulumi-supabase-analytics/sdk/go/logflare/internal"
)

var _ = internal.GetEnvOrDefault

type SourceNotifications struct {
	OtherEmailNotifications       string   `pulumi:"otherEmailNotifications"`
	TeamUserIdsForEmails          []string `pulumi:"teamUserIdsForEmails"`
	TeamUserIdsForSchemaUpdates   []string `pulumi:"teamUserIdsForSchemaUpdates"`
	TeamUserIdsForSms             []string `pulumi:"teamUserIdsForSms"`
	UserEmailNotifications        bool     `pulumi:"userEmailNotifications"`
	UserSchemaUpdateNotifications bool     `pulumi:"userSchemaUpdateNotifications"`
	UserTextNotifications         bool     `pulumi:"userTextNotifications"`
}

// SourceNotificationsInput is an input type that accepts SourceNotificationsArgs and SourceNotificationsOutput values.
// You can construct a concrete instance of `SourceNotificationsInput` via:
//
//	SourceNotificationsArgs{...}
type SourceNotificationsInput interface {
	pulumi.Input

	ToSourceNotificationsOutput() SourceNotificationsOutput
	ToSourceNotificationsOutputWithContext(context.Context) SourceNotificationsOutput
}

type SourceNotificationsArgs struct {
	OtherEmailNotifications       pulumi.StringInput      `pulumi:"otherEmailNotifications"`
	TeamUserIdsForEmails          pulumi.StringArrayInput `pulumi:"teamUserIdsForEmails"`
	TeamUserIdsForSchemaUpdates   pulumi.StringArrayInput `pulumi:"teamUserIdsForSchemaUpdates"`
	TeamUserIdsForSms             pulumi.StringArrayInput `pulumi:"teamUserIdsForSms"`
	UserEmailNotifications        pulumi.BoolInput        `pulumi:"userEmailNotifications"`
	UserSchemaUpdateNotifications pulumi.BoolInput        `pulumi:"userSchemaUpdateNotifications"`
	UserTextNotifications         pulumi.BoolInput        `pulumi:"userTextNotifications"`
}

func (SourceNotificationsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SourceNotifications)(nil)).Elem()
}

func (i SourceNotificationsArgs) ToSourceNotificationsOutput() SourceNotificationsOutput {
	return i.ToSourceNotificationsOutputWithContext(context.Background())
}

func (i SourceNotificationsArgs) ToSourceNotificationsOutputWithContext(ctx context.Context) SourceNotificationsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceNotificationsOutput)
}

func (i SourceNotificationsArgs) ToSourceNotificationsPtrOutput() SourceNotificationsPtrOutput {
	return i.ToSourceNotificationsPtrOutputWithContext(context.Background())
}

func (i SourceNotificationsArgs) ToSourceNotificationsPtrOutputWithContext(ctx context.Context) SourceNotificationsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceNotificationsOutput).ToSourceNotificationsPtrOutputWithContext(ctx)
}

// SourceNotificationsPtrInput is an input type that accepts SourceNotificationsArgs, SourceNotificationsPtr and SourceNotificationsPtrOutput values.
// You can construct a concrete instance of `SourceNotificationsPtrInput` via:
//
//	        SourceNotificationsArgs{...}
//
//	or:
//
//	        nil
type SourceNotificationsPtrInput interface {
	pulumi.Input

	ToSourceNotificationsPtrOutput() SourceNotificationsPtrOutput
	ToSourceNotificationsPtrOutputWithContext(context.Context) SourceNotificationsPtrOutput
}

type sourceNotificationsPtrType SourceNotificationsArgs

func SourceNotificationsPtr(v *SourceNotificationsArgs) SourceNotificationsPtrInput {
	return (*sourceNotificationsPtrType)(v)
}

func (*sourceNotificationsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**SourceNotifications)(nil)).Elem()
}

func (i *sourceNotificationsPtrType) ToSourceNotificationsPtrOutput() SourceNotificationsPtrOutput {
	return i.ToSourceNotificationsPtrOutputWithContext(context.Background())
}

func (i *sourceNotificationsPtrType) ToSourceNotificationsPtrOutputWithContext(ctx context.Context) SourceNotificationsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceNotificationsPtrOutput)
}

type SourceNotificationsOutput struct{ *pulumi.OutputState }

func (SourceNotificationsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SourceNotifications)(nil)).Elem()
}

func (o SourceNotificationsOutput) ToSourceNotificationsOutput() SourceNotificationsOutput {
	return o
}

func (o SourceNotificationsOutput) ToSourceNotificationsOutputWithContext(ctx context.Context) SourceNotificationsOutput {
	return o
}

func (o SourceNotificationsOutput) ToSourceNotificationsPtrOutput() SourceNotificationsPtrOutput {
	return o.ToSourceNotificationsPtrOutputWithContext(context.Background())
}

func (o SourceNotificationsOutput) ToSourceNotificationsPtrOutputWithContext(ctx context.Context) SourceNotificationsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v SourceNotifications) *SourceNotifications {
		return &v
	}).(SourceNotificationsPtrOutput)
}

func (o SourceNotificationsOutput) OtherEmailNotifications() pulumi.StringOutput {
	return o.ApplyT(func(v SourceNotifications) string { return v.OtherEmailNotifications }).(pulumi.StringOutput)
}

func (o SourceNotificationsOutput) TeamUserIdsForEmails() pulumi.StringArrayOutput {
	return o.ApplyT(func(v SourceNotifications) []string { return v.TeamUserIdsForEmails }).(pulumi.StringArrayOutput)
}

func (o SourceNotificationsOutput) TeamUserIdsForSchemaUpdates() pulumi.StringArrayOutput {
	return o.ApplyT(func(v SourceNotifications) []string { return v.TeamUserIdsForSchemaUpdates }).(pulumi.StringArrayOutput)
}

func (o SourceNotificationsOutput) TeamUserIdsForSms() pulumi.StringArrayOutput {
	return o.ApplyT(func(v SourceNotifications) []string { return v.TeamUserIdsForSms }).(pulumi.StringArrayOutput)
}

func (o SourceNotificationsOutput) UserEmailNotifications() pulumi.BoolOutput {
	return o.ApplyT(func(v SourceNotifications) bool { return v.UserEmailNotifications }).(pulumi.BoolOutput)
}

func (o SourceNotificationsOutput) UserSchemaUpdateNotifications() pulumi.BoolOutput {
	return o.ApplyT(func(v SourceNotifications) bool { return v.UserSchemaUpdateNotifications }).(pulumi.BoolOutput)
}

func (o SourceNotificationsOutput) UserTextNotifications() pulumi.BoolOutput {
	return o.ApplyT(func(v SourceNotifications) bool { return v.UserTextNotifications }).(pulumi.BoolOutput)
}

type SourceNotificationsPtrOutput struct{ *pulumi.OutputState }

func (SourceNotificationsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SourceNotifications)(nil)).Elem()
}

func (o SourceNotificationsPtrOutput) ToSourceNotificationsPtrOutput() SourceNotificationsPtrOutput {
	return o
}

func (o SourceNotificationsPtrOutput) ToSourceNotificationsPtrOutputWithContext(ctx context.Context) SourceNotificationsPtrOutput {
	return o
}

func (o SourceNotificationsPtrOutput) Elem() SourceNotificationsOutput {
	return o.ApplyT(func(v *SourceNotifications) SourceNotifications {
		if v != nil {
			return *v
		}
		var ret SourceNotifications
		return ret
	}).(SourceNotificationsOutput)
}

func (o SourceNotificationsPtrOutput) OtherEmailNotifications() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SourceNotifications) *string {
		if v == nil {
			return nil
		}
		return &v.OtherEmailNotifications
	}).(pulumi.StringPtrOutput)
}

func (o SourceNotificationsPtrOutput) TeamUserIdsForEmails() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SourceNotifications) []string {
		if v == nil {
			return nil
		}
		return v.TeamUserIdsForEmails
	}).(pulumi.StringArrayOutput)
}

func (o SourceNotificationsPtrOutput) TeamUserIdsForSchemaUpdates() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SourceNotifications) []string {
		if v == nil {
			return nil
		}
		return v.TeamUserIdsForSchemaUpdates
	}).(pulumi.StringArrayOutput)
}

func (o SourceNotificationsPtrOutput) TeamUserIdsForSms() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SourceNotifications) []string {
		if v == nil {
			return nil
		}
		return v.TeamUserIdsForSms
	}).(pulumi.StringArrayOutput)
}

func (o SourceNotificationsPtrOutput) UserEmailNotifications() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SourceNotifications) *bool {
		if v == nil {
			return nil
		}
		return &v.UserEmailNotifications
	}).(pulumi.BoolPtrOutput)
}

func (o SourceNotificationsPtrOutput) UserSchemaUpdateNotifications() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SourceNotifications) *bool {
		if v == nil {
			return nil
		}
		return &v.UserSchemaUpdateNotifications
	}).(pulumi.BoolPtrOutput)
}

func (o SourceNotificationsPtrOutput) UserTextNotifications() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SourceNotifications) *bool {
		if v == nil {
			return nil
		}
		return &v.UserTextNotifications
	}).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SourceNotificationsInput)(nil)).Elem(), SourceNotificationsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*SourceNotificationsPtrInput)(nil)).Elem(), SourceNotificationsArgs{})
	pulumi.RegisterOutputType(SourceNotificationsOutput{})
	pulumi.RegisterOutputType(SourceNotificationsPtrOutput{})
}
