// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package logflare

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/supabase/pulumi-supabase-analytics/sdk/go/logflare/internal"
)

type Source struct {
	pulumi.CustomResourceState

	// API quota for the source.
	ApiQuota pulumi.IntOutput `pulumi:"apiQuota"`
	// BigQuery table Time-To-Live (TTL) in days.
	BigqueryTableTtl pulumi.IntOutput `pulumi:"bigqueryTableTtl"`
	// BigQuery table ID.
	BqTableId pulumi.StringOutput `pulumi:"bqTableId"`
	// Custom event message keys.
	CustomEventMessageKeys pulumi.StringOutput `pulumi:"customEventMessageKeys"`
	// Whether the default ingest backend is enabled.
	DefaultIngestBackendEnabled pulumi.BoolOutput `pulumi:"defaultIngestBackendEnabled"`
	// Whether the source is marked as a favorite.
	Favorite pulumi.BoolOutput `pulumi:"favorite"`
	// Whether the source has rejected events.
	HasRejectedEvents pulumi.BoolOutput `pulumi:"hasRejectedEvents"`
	// Timestamp of when the source was created.
	InsertedAt pulumi.StringOutput `pulumi:"insertedAt"`
	// Metrics for the source, as a JSON string.
	Metrics pulumi.StringOutput `pulumi:"metrics"`
	// The name of the source.
	Name pulumi.StringOutput `pulumi:"name"`
	// Notification settings for the source.
	Notifications SourceNotificationsOutput `pulumi:"notifications"`
	// Public token for the source.
	PublicToken pulumi.StringOutput `pulumi:"publicToken"`
	// Slack webhook URL for notifications.
	SlackHookUrl pulumi.StringOutput `pulumi:"slackHookUrl"`
	// Private token for the source.
	Token pulumi.StringOutput `pulumi:"token"`
	// Timestamp of when the source was last updated.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// Webhook URL for notifications.
	WebhookNotificationUrl pulumi.StringOutput `pulumi:"webhookNotificationUrl"`
}

// NewSource registers a new resource with the given unique name, arguments, and options.
func NewSource(ctx *pulumi.Context,
	name string, args *SourceArgs, opts ...pulumi.ResourceOption) (*Source, error) {
	if args == nil {
		args = &SourceArgs{}
	}

	if args.SlackHookUrl != nil {
		args.SlackHookUrl = pulumi.ToSecret(args.SlackHookUrl).(pulumi.StringPtrInput)
	}
	if args.WebhookNotificationUrl != nil {
		args.WebhookNotificationUrl = pulumi.ToSecret(args.WebhookNotificationUrl).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"publicToken",
		"slackHookUrl",
		"token",
		"webhookNotificationUrl",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Source
	err := ctx.RegisterResource("logflare:index/source:Source", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSource gets an existing Source resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSource(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SourceState, opts ...pulumi.ResourceOption) (*Source, error) {
	var resource Source
	err := ctx.ReadResource("logflare:index/source:Source", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Source resources.
type sourceState struct {
	// API quota for the source.
	ApiQuota *int `pulumi:"apiQuota"`
	// BigQuery table Time-To-Live (TTL) in days.
	BigqueryTableTtl *int `pulumi:"bigqueryTableTtl"`
	// BigQuery table ID.
	BqTableId *string `pulumi:"bqTableId"`
	// Custom event message keys.
	CustomEventMessageKeys *string `pulumi:"customEventMessageKeys"`
	// Whether the default ingest backend is enabled.
	DefaultIngestBackendEnabled *bool `pulumi:"defaultIngestBackendEnabled"`
	// Whether the source is marked as a favorite.
	Favorite *bool `pulumi:"favorite"`
	// Whether the source has rejected events.
	HasRejectedEvents *bool `pulumi:"hasRejectedEvents"`
	// Timestamp of when the source was created.
	InsertedAt *string `pulumi:"insertedAt"`
	// Metrics for the source, as a JSON string.
	Metrics *string `pulumi:"metrics"`
	// The name of the source.
	Name *string `pulumi:"name"`
	// Notification settings for the source.
	Notifications *SourceNotifications `pulumi:"notifications"`
	// Public token for the source.
	PublicToken *string `pulumi:"publicToken"`
	// Slack webhook URL for notifications.
	SlackHookUrl *string `pulumi:"slackHookUrl"`
	// Private token for the source.
	Token *string `pulumi:"token"`
	// Timestamp of when the source was last updated.
	UpdatedAt *string `pulumi:"updatedAt"`
	// Webhook URL for notifications.
	WebhookNotificationUrl *string `pulumi:"webhookNotificationUrl"`
}

type SourceState struct {
	// API quota for the source.
	ApiQuota pulumi.IntPtrInput
	// BigQuery table Time-To-Live (TTL) in days.
	BigqueryTableTtl pulumi.IntPtrInput
	// BigQuery table ID.
	BqTableId pulumi.StringPtrInput
	// Custom event message keys.
	CustomEventMessageKeys pulumi.StringPtrInput
	// Whether the default ingest backend is enabled.
	DefaultIngestBackendEnabled pulumi.BoolPtrInput
	// Whether the source is marked as a favorite.
	Favorite pulumi.BoolPtrInput
	// Whether the source has rejected events.
	HasRejectedEvents pulumi.BoolPtrInput
	// Timestamp of when the source was created.
	InsertedAt pulumi.StringPtrInput
	// Metrics for the source, as a JSON string.
	Metrics pulumi.StringPtrInput
	// The name of the source.
	Name pulumi.StringPtrInput
	// Notification settings for the source.
	Notifications SourceNotificationsPtrInput
	// Public token for the source.
	PublicToken pulumi.StringPtrInput
	// Slack webhook URL for notifications.
	SlackHookUrl pulumi.StringPtrInput
	// Private token for the source.
	Token pulumi.StringPtrInput
	// Timestamp of when the source was last updated.
	UpdatedAt pulumi.StringPtrInput
	// Webhook URL for notifications.
	WebhookNotificationUrl pulumi.StringPtrInput
}

func (SourceState) ElementType() reflect.Type {
	return reflect.TypeOf((*sourceState)(nil)).Elem()
}

type sourceArgs struct {
	// API quota for the source.
	ApiQuota *int `pulumi:"apiQuota"`
	// BigQuery table Time-To-Live (TTL) in days.
	BigqueryTableTtl *int `pulumi:"bigqueryTableTtl"`
	// BigQuery table ID.
	BqTableId *string `pulumi:"bqTableId"`
	// Custom event message keys.
	CustomEventMessageKeys *string `pulumi:"customEventMessageKeys"`
	// Whether the default ingest backend is enabled.
	DefaultIngestBackendEnabled *bool `pulumi:"defaultIngestBackendEnabled"`
	// Whether the source is marked as a favorite.
	Favorite *bool `pulumi:"favorite"`
	// Metrics for the source, as a JSON string.
	Metrics *string `pulumi:"metrics"`
	// The name of the source.
	Name *string `pulumi:"name"`
	// Notification settings for the source.
	Notifications *SourceNotifications `pulumi:"notifications"`
	// Slack webhook URL for notifications.
	SlackHookUrl *string `pulumi:"slackHookUrl"`
	// Webhook URL for notifications.
	WebhookNotificationUrl *string `pulumi:"webhookNotificationUrl"`
}

// The set of arguments for constructing a Source resource.
type SourceArgs struct {
	// API quota for the source.
	ApiQuota pulumi.IntPtrInput
	// BigQuery table Time-To-Live (TTL) in days.
	BigqueryTableTtl pulumi.IntPtrInput
	// BigQuery table ID.
	BqTableId pulumi.StringPtrInput
	// Custom event message keys.
	CustomEventMessageKeys pulumi.StringPtrInput
	// Whether the default ingest backend is enabled.
	DefaultIngestBackendEnabled pulumi.BoolPtrInput
	// Whether the source is marked as a favorite.
	Favorite pulumi.BoolPtrInput
	// Metrics for the source, as a JSON string.
	Metrics pulumi.StringPtrInput
	// The name of the source.
	Name pulumi.StringPtrInput
	// Notification settings for the source.
	Notifications SourceNotificationsPtrInput
	// Slack webhook URL for notifications.
	SlackHookUrl pulumi.StringPtrInput
	// Webhook URL for notifications.
	WebhookNotificationUrl pulumi.StringPtrInput
}

func (SourceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*sourceArgs)(nil)).Elem()
}

type SourceInput interface {
	pulumi.Input

	ToSourceOutput() SourceOutput
	ToSourceOutputWithContext(ctx context.Context) SourceOutput
}

func (*Source) ElementType() reflect.Type {
	return reflect.TypeOf((**Source)(nil)).Elem()
}

func (i *Source) ToSourceOutput() SourceOutput {
	return i.ToSourceOutputWithContext(context.Background())
}

func (i *Source) ToSourceOutputWithContext(ctx context.Context) SourceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceOutput)
}

// SourceArrayInput is an input type that accepts SourceArray and SourceArrayOutput values.
// You can construct a concrete instance of `SourceArrayInput` via:
//
//	SourceArray{ SourceArgs{...} }
type SourceArrayInput interface {
	pulumi.Input

	ToSourceArrayOutput() SourceArrayOutput
	ToSourceArrayOutputWithContext(context.Context) SourceArrayOutput
}

type SourceArray []SourceInput

func (SourceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Source)(nil)).Elem()
}

func (i SourceArray) ToSourceArrayOutput() SourceArrayOutput {
	return i.ToSourceArrayOutputWithContext(context.Background())
}

func (i SourceArray) ToSourceArrayOutputWithContext(ctx context.Context) SourceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceArrayOutput)
}

// SourceMapInput is an input type that accepts SourceMap and SourceMapOutput values.
// You can construct a concrete instance of `SourceMapInput` via:
//
//	SourceMap{ "key": SourceArgs{...} }
type SourceMapInput interface {
	pulumi.Input

	ToSourceMapOutput() SourceMapOutput
	ToSourceMapOutputWithContext(context.Context) SourceMapOutput
}

type SourceMap map[string]SourceInput

func (SourceMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Source)(nil)).Elem()
}

func (i SourceMap) ToSourceMapOutput() SourceMapOutput {
	return i.ToSourceMapOutputWithContext(context.Background())
}

func (i SourceMap) ToSourceMapOutputWithContext(ctx context.Context) SourceMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceMapOutput)
}

type SourceOutput struct{ *pulumi.OutputState }

func (SourceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Source)(nil)).Elem()
}

func (o SourceOutput) ToSourceOutput() SourceOutput {
	return o
}

func (o SourceOutput) ToSourceOutputWithContext(ctx context.Context) SourceOutput {
	return o
}

// API quota for the source.
func (o SourceOutput) ApiQuota() pulumi.IntOutput {
	return o.ApplyT(func(v *Source) pulumi.IntOutput { return v.ApiQuota }).(pulumi.IntOutput)
}

// BigQuery table Time-To-Live (TTL) in days.
func (o SourceOutput) BigqueryTableTtl() pulumi.IntOutput {
	return o.ApplyT(func(v *Source) pulumi.IntOutput { return v.BigqueryTableTtl }).(pulumi.IntOutput)
}

// BigQuery table ID.
func (o SourceOutput) BqTableId() pulumi.StringOutput {
	return o.ApplyT(func(v *Source) pulumi.StringOutput { return v.BqTableId }).(pulumi.StringOutput)
}

// Custom event message keys.
func (o SourceOutput) CustomEventMessageKeys() pulumi.StringOutput {
	return o.ApplyT(func(v *Source) pulumi.StringOutput { return v.CustomEventMessageKeys }).(pulumi.StringOutput)
}

// Whether the default ingest backend is enabled.
func (o SourceOutput) DefaultIngestBackendEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Source) pulumi.BoolOutput { return v.DefaultIngestBackendEnabled }).(pulumi.BoolOutput)
}

// Whether the source is marked as a favorite.
func (o SourceOutput) Favorite() pulumi.BoolOutput {
	return o.ApplyT(func(v *Source) pulumi.BoolOutput { return v.Favorite }).(pulumi.BoolOutput)
}

// Whether the source has rejected events.
func (o SourceOutput) HasRejectedEvents() pulumi.BoolOutput {
	return o.ApplyT(func(v *Source) pulumi.BoolOutput { return v.HasRejectedEvents }).(pulumi.BoolOutput)
}

// Timestamp of when the source was created.
func (o SourceOutput) InsertedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Source) pulumi.StringOutput { return v.InsertedAt }).(pulumi.StringOutput)
}

// Metrics for the source, as a JSON string.
func (o SourceOutput) Metrics() pulumi.StringOutput {
	return o.ApplyT(func(v *Source) pulumi.StringOutput { return v.Metrics }).(pulumi.StringOutput)
}

// The name of the source.
func (o SourceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Source) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Notification settings for the source.
func (o SourceOutput) Notifications() SourceNotificationsOutput {
	return o.ApplyT(func(v *Source) SourceNotificationsOutput { return v.Notifications }).(SourceNotificationsOutput)
}

// Public token for the source.
func (o SourceOutput) PublicToken() pulumi.StringOutput {
	return o.ApplyT(func(v *Source) pulumi.StringOutput { return v.PublicToken }).(pulumi.StringOutput)
}

// Slack webhook URL for notifications.
func (o SourceOutput) SlackHookUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *Source) pulumi.StringOutput { return v.SlackHookUrl }).(pulumi.StringOutput)
}

// Private token for the source.
func (o SourceOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *Source) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

// Timestamp of when the source was last updated.
func (o SourceOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Source) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// Webhook URL for notifications.
func (o SourceOutput) WebhookNotificationUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *Source) pulumi.StringOutput { return v.WebhookNotificationUrl }).(pulumi.StringOutput)
}

type SourceArrayOutput struct{ *pulumi.OutputState }

func (SourceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Source)(nil)).Elem()
}

func (o SourceArrayOutput) ToSourceArrayOutput() SourceArrayOutput {
	return o
}

func (o SourceArrayOutput) ToSourceArrayOutputWithContext(ctx context.Context) SourceArrayOutput {
	return o
}

func (o SourceArrayOutput) Index(i pulumi.IntInput) SourceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Source {
		return vs[0].([]*Source)[vs[1].(int)]
	}).(SourceOutput)
}

type SourceMapOutput struct{ *pulumi.OutputState }

func (SourceMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Source)(nil)).Elem()
}

func (o SourceMapOutput) ToSourceMapOutput() SourceMapOutput {
	return o
}

func (o SourceMapOutput) ToSourceMapOutputWithContext(ctx context.Context) SourceMapOutput {
	return o
}

func (o SourceMapOutput) MapIndex(k pulumi.StringInput) SourceOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Source {
		return vs[0].(map[string]*Source)[vs[1].(string)]
	}).(SourceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SourceInput)(nil)).Elem(), &Source{})
	pulumi.RegisterInputType(reflect.TypeOf((*SourceArrayInput)(nil)).Elem(), SourceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SourceMapInput)(nil)).Elem(), SourceMap{})
	pulumi.RegisterOutputType(SourceOutput{})
	pulumi.RegisterOutputType(SourceArrayOutput{})
	pulumi.RegisterOutputType(SourceMapOutput{})
}
