// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Logflare.Outputs
{

    [OutputType]
    public sealed class SourceNotifications
    {
        public readonly string OtherEmailNotifications;
        public readonly ImmutableArray<string> TeamUserIdsForEmails;
        public readonly ImmutableArray<string> TeamUserIdsForSchemaUpdates;
        public readonly ImmutableArray<string> TeamUserIdsForSms;
        public readonly bool UserEmailNotifications;
        public readonly bool UserSchemaUpdateNotifications;
        public readonly bool UserTextNotifications;

        [OutputConstructor]
        private SourceNotifications(
            string otherEmailNotifications,

            ImmutableArray<string> teamUserIdsForEmails,

            ImmutableArray<string> teamUserIdsForSchemaUpdates,

            ImmutableArray<string> teamUserIdsForSms,

            bool userEmailNotifications,

            bool userSchemaUpdateNotifications,

            bool userTextNotifications)
        {
            OtherEmailNotifications = otherEmailNotifications;
            TeamUserIdsForEmails = teamUserIdsForEmails;
            TeamUserIdsForSchemaUpdates = teamUserIdsForSchemaUpdates;
            TeamUserIdsForSms = teamUserIdsForSms;
            UserEmailNotifications = userEmailNotifications;
            UserSchemaUpdateNotifications = userSchemaUpdateNotifications;
            UserTextNotifications = userTextNotifications;
        }
    }
}
