// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/supabase/pulumi-supabase-analytics/sdk/go/logflare/internal"
)

var _ = internal.GetEnvOrDefault

// Access Token for Logflare API. May also be provided via LOGFLARE_ACCESS_TOKEN environment variable.
func GetAccessToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "logflare:accessToken")
}

// URI for Logflare API. Defaults to 'https://logflare.app'.
func GetHost(ctx *pulumi.Context) string {
	return config.Get(ctx, "logflare:host")
}
