// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Logflare.Inputs
{

    public sealed class SourceNotificationsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("otherEmailNotifications", required: true)]
        public Input<string> OtherEmailNotifications { get; set; } = null!;

        [Input("teamUserIdsForEmails", required: true)]
        private InputList<string>? _teamUserIdsForEmails;
        public InputList<string> TeamUserIdsForEmails
        {
            get => _teamUserIdsForEmails ?? (_teamUserIdsForEmails = new InputList<string>());
            set => _teamUserIdsForEmails = value;
        }

        [Input("teamUserIdsForSchemaUpdates", required: true)]
        private InputList<string>? _teamUserIdsForSchemaUpdates;
        public InputList<string> TeamUserIdsForSchemaUpdates
        {
            get => _teamUserIdsForSchemaUpdates ?? (_teamUserIdsForSchemaUpdates = new InputList<string>());
            set => _teamUserIdsForSchemaUpdates = value;
        }

        [Input("teamUserIdsForSms", required: true)]
        private InputList<string>? _teamUserIdsForSms;
        public InputList<string> TeamUserIdsForSms
        {
            get => _teamUserIdsForSms ?? (_teamUserIdsForSms = new InputList<string>());
            set => _teamUserIdsForSms = value;
        }

        [Input("userEmailNotifications", required: true)]
        public Input<bool> UserEmailNotifications { get; set; } = null!;

        [Input("userSchemaUpdateNotifications", required: true)]
        public Input<bool> UserSchemaUpdateNotifications { get; set; } = null!;

        [Input("userTextNotifications", required: true)]
        public Input<bool> UserTextNotifications { get; set; } = null!;

        public SourceNotificationsGetArgs()
        {
        }
        public static new SourceNotificationsGetArgs Empty => new SourceNotificationsGetArgs();
    }
}
